/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Dao } from "./Dao";
export type { Erc20 } from "./Erc20";
export type { Greeter } from "./Greeter";
export type { TestContract } from "./TestContract";
